version: "3"
services: 
  gobackup:
    restart: always
    container_name: gobackup
    image: tonghs/gobackup:latest

    environment:
      - BAK_SCHEDULE=* * * * *

    volumes: 
      - ./conf/:/etc/gobackup/
      - ./data/backups/:/data/backups/
