version: "3"
services: 
 auto-sqlback:
  restart: always
  container_name: auto-sqlbak
  image: tonghs/gobackup:latest

  environment:
    - BAK_SCHEDULE=* * * * *

  volumes: 
    - ./conf/:/etc/gobackup/
    - ./data/backups/:/data/backups/
